### ISSUE TITLE
Fiddle not available

### ISSUE THREAD

**Issue by agarcialeon** [oxyplot/oxyplot-fiddle#6]
Currently the fiddle website is not accesible. It is down?
I would like also to link this [issue]( https://github.com/oxyplot/oxyplot/issues/1311) to provide better documention for Oxyplot.

**Comment by objorke** [comment]
Yes, the website is currently taken down. I agree it would be good to implement it with Blazor, too!

**Comment by objorke** [comment]
Updated to 2.0: https://oxyplot-fiddle.azurewebsites.net/
